config/routes.rb
Blog::Application.routes.draw do
  get "welcome/index"
 
  resources :articles 
  root 'welcome#index'

  

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def new
	end
#	def create
#  		render plain: params[:article].inspect
#	end
#	def create
#  		@article = Article.new(params[:article])
# 		@article.save
#  		redirect_to @article
#	end
# for showing articles back 
def show
  @article = Article.find(params[:id])
end
def index
  @articles = Article.all
end
	def create
 		 @article = Article.new(article_params)
  		@article.save
  		redirect_to @article
		end 
private
  	def article_params
    		params.require(:article).permit(:title, :text)
  	end
	
#public
# for showing articles back 	
#``	def show
#  		@article = Article.find(params[:id])
#	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<h1>All blog posts of senthil</h1>
#<%= link_to 'Want to write a New article ? ', new_article_path %>
<%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<center><h1>new blog post</h1>

<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', articles_path %>
</center>

app/views/articles/show.html.erb
<p>
<strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1> hi this is senthil ramasamy saying "hello world !"</h1>
<h1>blog of senthil :  articles</h1>
<%= link_to 'My Blog', controller: 'articles' %>